### ISSUE TITLE
`+{props.CA.ca.X_ALU_COM_DLCarrierAggregationNumberOfEntries}` 

### ISSUE THREAD

**Issue by AndrewPardoe** [highvolt-dev/tmo-live-graph#6]
I won't be very useful in debugging an React app, but this is what shows on my screen.

![image](https://user-images.githubusercontent.com/9937771/149643715-d8450a1f-e6b6-414f-8051-3cfdd0ddbdb2.png)

**Comment by highvolt-dev** [comment]
Thanks for reporting, @AndrewPardoe 

This should now be fixed. I was testing against someone else's signal to implement carrier aggregation info because my own gateway does not normally connect to additional bands. I ended up changing the formatting of the CA information after switching to my actual signal and made a mistake that didn't get caught til you filed your report. Thanks again!
